# Landing + téléchargements — bassorder.smegg.cloud
server {
    listen 80;
    listen [::]:80;
    server_name bassorder.smegg.cloud;

    root /var/www/bassorder;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /downloads/ {
        alias /var/www/bassorder/downloads/;
        add_header Content-Disposition 'attachment';
        types {
            application/octet-stream msi exe;
        }
    }
}
